# Generated by Django 5.1.5 on 2026-09-18 17:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("poscheck", "0001_initial"),
        ("precheck", "0002_check_execution_async"),
    ]

    operations = [
        migrations.AddField(
            model_name="poscheckresult",
            name="execution",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="poscheck_results",
                to="precheck.checkexecution",
            ),
        ),
    ]
