# Generated by Django 5.2.8 on 2026-09-11 16:56

import uuid

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("ep_import", "0004_importjob_created_by"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CheckAnalysis",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "technology",
                    models.CharField(db_index=True, default="5G", max_length=8),
                ),
                ("site_name", models.CharField(max_length=255)),
                ("selected_cells", models.JSONField(blank=True, default=list)),
                ("pre_check", models.BooleanField(default=False)),
                ("full_check", models.BooleanField(default=False)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("awaiting_returns", "Awaiting returns"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("inconsistent", "Inconsistent"),
                            ("failed", "Failed"),
                        ],
                        db_index=True,
                        default="draft",
                        max_length=32,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(db_index=True, default=django.utils.timezone.now),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="check_analyses",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "ep_job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="check_analyses",
                        to="ep_import.importjob",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="CheckReturnFile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "check_type",
                    models.CharField(
                        choices=[
                            ("precheck", "Pre-check"),
                            ("full_check", "Full Check"),
                        ],
                        db_index=True,
                        max_length=16,
                    ),
                ),
                ("original_filename", models.CharField(max_length=255)),
                ("stored_file", models.FileField(upload_to="check_returns/%Y/%m/%d/")),
                (
                    "content_sha256",
                    models.CharField(blank=True, db_index=True, default="", max_length=64),
                ),
                (
                    "uploaded_at",
                    models.DateTimeField(db_index=True, default=django.utils.timezone.now),
                ),
                (
                    "analysis",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="return_files",
                        to="precheck.checkanalysis",
                    ),
                ),
            ],
            options={
                "ordering": ("-uploaded_at",),
            },
        ),
        migrations.CreateModel(
            name="PrecheckResult",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "overall_status",
                    models.CharField(
                        choices=[
                            ("completed", "Completed"),
                            ("inconsistent", "Inconsistent"),
                            ("execution_failure", "Execution failure"),
                        ],
                        db_index=True,
                        max_length=32,
                    ),
                ),
                ("validations", models.JSONField(blank=True, default=list)),
                ("extracted", models.JSONField(blank=True, default=dict)),
                ("error_code", models.CharField(blank=True, default="", max_length=64)),
                (
                    "error_title",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("error_detail", models.TextField(blank=True, default="")),
                (
                    "processed_at",
                    models.DateTimeField(db_index=True, default=django.utils.timezone.now),
                ),
                (
                    "analysis",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="precheck_result",
                        to="precheck.checkanalysis",
                    ),
                ),
            ],
            options={
                "ordering": ("-processed_at",),
            },
        ),
        migrations.AddIndex(
            model_name="checkanalysis",
            index=models.Index(
                fields=["ep_job", "technology", "site_name"],
                name="precheck_ch_ep_job__f319ae_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="checkreturnfile",
            constraint=models.UniqueConstraint(
                fields=("analysis", "check_type"), name="uniq_checkreturn_analysis_type"
            ),
        ),
    ]
