# Generated by Django 5.1.5 on 2026-09-18 17:11

import uuid

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("precheck", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CheckExecution",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "scope",
                    models.CharField(
                        choices=[
                            ("precheck", "Pre-check"),
                            ("full_check", "Full Check"),
                            ("both", "Pre-check and Full Check"),
                        ],
                        db_index=True,
                        max_length=16,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("success", "Success"),
                            ("failed", "Failed"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=16,
                    ),
                ),
                (
                    "stage",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("queued", "Queued"),
                            ("reading", "Reading"),
                            ("parsing", "Parsing"),
                            ("validating", "Validating"),
                            ("persisting", "Persisting"),
                            ("done", "Done"),
                            ("failed", "Failed"),
                        ],
                        default="queued",
                        max_length=16,
                    ),
                ),
                (
                    "selection_version",
                    models.CharField(blank=True, db_index=True, default="", max_length=64),
                ),
                (
                    "pre_return_sha256",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                (
                    "full_return_sha256",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                ("task_id", models.CharField(blank=True, default="", max_length=255)),
                (
                    "result_status",
                    models.CharField(blank=True, default="", max_length=32),
                ),
                ("error_code", models.CharField(blank=True, default="", max_length=64)),
                (
                    "error_title",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "redirect_url",
                    models.CharField(blank=True, default="", max_length=512),
                ),
                (
                    "created_at",
                    models.DateTimeField(db_index=True, default=django.utils.timezone.now),
                ),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                (
                    "analysis",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="executions",
                        to="precheck.checkanalysis",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="check_executions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
            },
        ),
        migrations.AddField(
            model_name="precheckresult",
            name="execution",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="precheck_results",
                to="precheck.checkexecution",
            ),
        ),
        migrations.AddIndex(
            model_name="checkexecution",
            index=models.Index(fields=["analysis", "status"], name="precheck_ch_analysi_bb442d_idx"),
        ),
        migrations.AddIndex(
            model_name="checkexecution",
            index=models.Index(
                fields=[
                    "analysis",
                    "selection_version",
                    "pre_return_sha256",
                    "full_return_sha256",
                ],
                name="precheck_ch_analysi_8e5984_idx",
            ),
        ),
    ]
