# Generated by Django 5.2.17 on 2026-09-21 17:48

import uuid

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ep_import", "0004_importjob_created_by"),
        ("precheck", "0002_check_execution_async"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CombinedCheck",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("technologies", models.JSONField(blank=True, default=list)),
                ("site_names", models.JSONField(blank=True, default=list)),
                ("pre_check", models.BooleanField(default=False)),
                ("full_check", models.BooleanField(default=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("awaiting_returns", "Awaiting returns"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("inconsistent", "Inconsistent"),
                            ("failed", "Failed"),
                        ],
                        db_index=True,
                        default="draft",
                        max_length=32,
                    ),
                ),
                ("created_at", models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="combined_checks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "ep_job",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="combined_checks",
                        to="ep_import.importjob",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
            },
        ),
        migrations.AddField(
            model_name="checkanalysis",
            name="combined_check",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="analyses",
                to="precheck.combinedcheck",
            ),
        ),
        migrations.AddIndex(
            model_name="checkanalysis",
            index=models.Index(fields=["combined_check", "technology"], name="precheck_ch_combine_a3f6af_idx"),
        ),
    ]
